# Generated by Django 5.1.6 on 2025-03-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_test', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='PreguntaDelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.IntegerField()),
                ('normativa', models.CharField(max_length=100)),
                ('pregunta', models.TextField()),
                ('opcion_a', models.TextField()),
                ('opcion_b', models.TextField()),
                ('opcion_c', models.TextField()),
                ('opcion_d', models.TextField(blank=True, null=True)),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('justificacion', models.TextField()),
                ('nombre_del_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_administradores.test')),
            ],
            options={
                'verbose_name': 'Pregunta Del Test',
                'verbose_name_plural': 'Preguntas de los Tests',
            },
        ),
    ]
