# Generated by Django 5.2 on 2025-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0002_remove_preguntadeltest_nombre_del_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='normativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tema',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
