# Generated by Django 5.2 on 2025-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0003_test_normativa_test_tema_test_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntadeltest',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntadeltest',
            name='normativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preguntadeltest',
            name='tema',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
