# Generated by Django 5.2 on 2025-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0004_preguntadeltest_year_alter_preguntadeltest_normativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tipo',
            field=models.CharField(choices=[('normativa', 'Normativa'), ('año', 'Año'), ('tema', 'Tema'), ('aleatorio', 'Aleatorio')], default='aleatorio', max_length=10),
        ),
    ]
