# Generated by Django 5.2 on 2025-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0006_alter_test_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tipo',
            field=models.CharField(choices=[('normativa', 'Normativa'), ('año', 'Año'), ('tema', 'Tema'), ('sin especificar', 'Sin especificar')], default='sin especificar', max_length=20),
        ),
    ]
