# Generated by Django 5.2 on 2025-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0007_alter_test_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Año'),
        ),
    ]
