# Generated by Django 5.2 on 2025-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0008_alter_test_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntadeltest',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
