# Generated by Django 5.2 on 2025-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0009_alter_preguntadeltest_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='nombre_del_test',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
