# Generated by Django 5.2 on 2025-04-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0010_alter_test_nombre_del_test_alter_test_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='normativa',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tema',
        ),
    ]
