# Generated by Django 5.2 on 2025-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0011_remove_test_normativa_remove_test_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='fue_generado_proceduralmente',
            field=models.BooleanField(default=True, verbose_name='Este test fue generado proceduralmente?'),
        ),
    ]
