# Generated by Django 5.1.6 on 2025-03-12 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_administradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionDelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_del_fin_del_test', models.DateTimeField(blank=True, null=True)),
                # ('limite_de_tiempo', models.IntegerField(default=1800)),    # El límite de tiempo en segundos (30 min)
                ('limite_de_tiempo', models.IntegerField(default=60)),  # El límite de tiempo en segundos (1 min)
                ('nombre_del_test', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('esta_terminado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaDelUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcto', models.BooleanField(default=False)),
                ('respuesta_seleccionada', models.CharField(max_length=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_administradores.preguntadeltest')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_clientes.sesiondeltest')),
            ],
        ),
    ]
