# Generated by Django 5.1.6 on 2025-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesiondeltest',
            old_name='esta_terminado',
            new_name='cliente_entrego_este_test',
        ),
    ]
