# Generated by Django 5.1.6 on 2025-03-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0001_initial'),
        ('tests_clientes', '0002_rename_esta_terminado_sesiondeltest_cliente_entrego_este_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiondeltest',
            name='nombre_del_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_administradores.test'),
        ),
    ]
