# Generated by Django 5.1.6 on 2025-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0003_alter_sesiondeltest_nombre_del_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondeltest',
            name='nivel_de_dificultad',
            field=models.CharField(default='Errores no restan puntos', max_length=50),
        ),
    ]
