# Generated by Django 5.1.6 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0005_alter_sesiondeltest_limite_de_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondeltest',
            name='tiempo_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
