# Generated by Django 5.1.6 on 2025-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0006_sesiondeltest_tiempo_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondeltest',
            name='preguntas_seleccionadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
