# Generated by Django 5.1.6 on 2025-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0007_sesiondeltest_preguntas_seleccionadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesiondeltest',
            name='preguntas_seleccionadas',
        ),
        migrations.AddField(
            model_name='sesiondeltest',
            name='test_autocorregido',
            field=models.BooleanField(default=False),
        ),
    ]
