# Generated by Django 5.2 on 2025-04-25 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0010_alter_test_nombre_del_test_alter_test_year'),
        ('tests_clientes', '0008_remove_sesiondeltest_preguntas_seleccionadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasGuardadasPorElUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_administradores.preguntadeltest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_administradores.test')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
