# Generated by Django 5.2 on 2025-04-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0009_preguntasguardadasporelusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasguardadasporelusuario',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_clientes.sesiondeltest'),
        ),
    ]
