# Generated by Django 5.2 on 2025-04-28 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_administradores', '0010_alter_test_nombre_del_test_alter_test_year'),
        ('tests_clientes', '0010_preguntasguardadasporelusuario_sesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreguntasGuardadasPorElUsuario',
            new_name='PreguntaGuardadaPorElUsuario',
        ),
    ]
