# Generated by Django 5.2 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_clientes', '0011_rename_preguntasguardadasporelusuario_preguntaguardadaporelusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiondeltest',
            name='limite_de_tiempo',
            field=models.IntegerField(blank=True, default=1800, null=True),
        ),
    ]
